import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { MonthlyStats } from "./monthly";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 11,
    color: "#201d18",
    fontFamily: "Helvetica",
  },
  brand: {
    fontSize: 14,
    fontWeight: 700,
    color: "#4f7dfd",
    marginBottom: 4,
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 11,
    color: "#6b6b6b",
    marginBottom: 24,
  },
  statsRow: {
    flexDirection: "row",
    marginBottom: 28,
    borderTop: "1 solid #dddddd",
    borderBottom: "1 solid #dddddd",
    paddingVertical: 14,
  },
  stat: {
    flex: 1,
  },
  statValue: {
    fontSize: 22,
    fontWeight: 700,
  },
  statLabel: {
    fontSize: 9,
    color: "#6b6b6b",
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 10,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottom: "1 solid #201d18",
    paddingBottom: 6,
    marginBottom: 6,
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1 solid #eeeeee",
    paddingVertical: 6,
  },
  colOutlet: { flex: 2 },
  colAuthority: { flex: 1 },
  colType: { flex: 1 },
  colDate: { flex: 1 },
  headerCell: { fontSize: 9, color: "#6b6b6b" },
  cell: { fontSize: 10 },
  empty: {
    fontSize: 10,
    color: "#6b6b6b",
    marginTop: 8,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#9a9a9a",
  },
});

function formatMonth(month: string) {
  const [year, m] = month.split("-").map(Number);
  return new Date(Date.UTC(year, m - 1, 1)).toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

export function MonthlyReportDocument({ stats }: { stats: MonthlyStats }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>Quotarly</Text>
        <Text style={styles.title}>Monthly report — {formatMonth(stats.month)}</Text>
        <Text style={styles.subtitle}>{stats.expertName}</Text>

        <View style={styles.statsRow}>
          <View style={styles.stat}>
            <Text style={styles.statValue}>{stats.pitchesSent}</Text>
            <Text style={styles.statLabel}>Pitches sent</Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statValue}>{stats.backlinksWon}</Text>
            <Text style={styles.statLabel}>Backlinks won</Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statValue}>
              {stats.avgAuthority ?? "—"}
            </Text>
            <Text style={styles.statLabel}>Average authority score</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Backlinks this month</Text>

        {stats.backlinks.length > 0 ? (
          <View>
            <View style={styles.tableHeader}>
              <Text style={[styles.headerCell, styles.colOutlet]}>Outlet</Text>
              <Text style={[styles.headerCell, styles.colAuthority]}>
                Authority
              </Text>
              <Text style={[styles.headerCell, styles.colType]}>Type</Text>
              <Text style={[styles.headerCell, styles.colDate]}>Date</Text>
            </View>
            {stats.backlinks.map((b, i) => (
              <View key={i} style={styles.tableRow}>
                <Text style={[styles.cell, styles.colOutlet]}>
                  {b.outletDomain}
                </Text>
                <Text style={[styles.cell, styles.colAuthority]}>
                  {b.authorityScore ?? "—"}
                </Text>
                <Text style={[styles.cell, styles.colType]}>
                  {b.isDofollow ? "dofollow" : "nofollow"}
                </Text>
                <Text style={[styles.cell, styles.colDate]}>
                  {new Date(b.firstSeenAt).toLocaleDateString("en-US", {
                    timeZone: "UTC",
                  })}
                </Text>
              </View>
            ))}
          </View>
        ) : (
          <Text style={styles.empty}>No backlinks confirmed this month.</Text>
        )}

        <Text style={styles.footer}>
          Generated by Quotarly · quotarly.com · Numbers reflect this
          account's real activity, not an estimate.
        </Text>
      </Page>
    </Document>
  );
}
